### ISSUE TITLE
Support sweet_xml 0.7

### ISSUE THREAD

**Issue by 23Skidoo** [elixir-soap/soap#101]
`sweet_xml` 0.7 was released in July 2021. There are already some libraries like `ex_aws` that [specify `sweet_xml ~> 0.7` in their dependencies](https://github.com/ex-aws/ex_aws/blob/c59ae58ab397cf9eb4c82f590c5c91efafe7f134/mix.exs#L52), which results in an error when `ex_aws` and `soap` are used together.

**Comment by eckmanca-caremore** [comment]
FYI. Switching to use Hex instead of Github works for allowing the override to work.
Change:
  `{:soap, git: "https://github.com/potok-digital/soap", tag: "master"}`
to:
  `{:soap, "~> 1.1.0"}`

**Comment by cgarvis** [comment]
This shouldn't be an issue due to #97
