### ISSUE TITLE
Operations not found in our WSDL

### ISSUE THREAD

**Issue by lejoko** [elixir-soap/soap#67]
Hi,
we waited for your release and tried 1.0.1. We still have problems with your library.

Here is our wsdl file 
[api.wsdl.txt](https://github.com/elixir-soap/soap/files/2865595/api.wsdl.txt)

When we parse it no operations are found, and therefore we can't call any action:
```
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, wsdl} = Soap.init_model("api.wsdl.xml", :file)
{:ok,
 %{
(... very long output...)
 }}
iex(2)> Soap.operations(wsdl)                               
[]
iex(3)> 
```

Obviously, operations should not be empty.

**Comment by sigmen** [comment]
Hi, thanks for comment, i will research this problem at soon or you can make the pr for resolve this :)

**Comment by Nitrino** [comment]
@sigmen do you have any progress with it?

**Comment by Espina2** [comment]
We did not work either with the european vat validition service. Link here:
http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

**Comment by cscholle1** [comment]
Might be related...

I just ran into all `soapAction=""` in my wsdl. They will not show up in `Soap.operations` because they are rejected in `wsdl.ex`:

<pre>
  defp get_operations(wsdl, protocol_ns, soap_ns) do
    wsdl
    |> xpath(~x"//#{ns("definitions", protocol_ns)}/#{ns("binding", protocol_ns)}/#{ns("operation", protocol_ns)}"l)
    |> Enum.map(fn node ->
      node
      |> xpath(~x".", name: ~x"./@name"s, soap_action: ~x"./#{ns("operation", soap_ns)}/@soapAction"s)
      |> Map.put(:input, get_operation_input(node, protocol_ns, soap_ns))
    end)
    <b>|> Enum.reject(fn x -> x[:soap_action] == "" end)</b>
  end
</pre>

@sigmen @Nitrino This may not have been a use case identified yet?

**Comment by danadaldos** [comment]
@cscholle1 

I am having the same difficulty on an Experian API that has blank values for `soapAction` : https://www.experian.com/Vingateway/VinGatewayPort?wsdl
