### ISSUE TITLE
Expose HTTPoison config

### ISSUE THREAD

**Issue by youalreadydid** [elixir-soap/soap#71]
Hi,

I need to configure HTTPoison in Soap.init_model(_, :url) to have a :recv_timeout bigger than the default (5s). Is possible to expose the configuration in some way? Thanks!

**Comment by Nitrino** [comment]
Hi @youalreadydid. 
You can pass HTTPoison options by the last parameter to `Soap.call/5`.
Details about `Soap.call/5` in docs: https://hexdocs.pm/soap/Soap.html#call/5

**Comment by Nitrino** [comment]
Oh, sorry you mean `Soap.init_model/2` function. 
I think we should add a parameter by analogy with `Soap.call/5`. 
I will add this in the next few days.
